### ISSUE TITLE
Android SDK fails when trying to parse "short" date using "long" formatting pattern

### ISSUE THREAD

**Issue by kord2003** [Medable/Android-SDK#1]
Error occurs when I'm trying to create a new PatientFile or retrieve existing PatientFiles

APIClient.listPatientFiles(...)
APIClient.createPatientFile(...)

java.text.ParseException: Unparseable date: "1987-07-31" (at offset 10)
03-22 12:59:32.897 28344-28344/com.example.smilio W/System.err:     at java.text.DateFormat.parse(DateFormat.java:555)
03-22 12:59:32.897 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.Utils.dateFromString(Utils.java:116)
03-22 12:59:32.897 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.Utils.parseValueOrNull(Utils.java:193)
03-22 12:59:32.897 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.model.ContextObjects.PatientFile.updateWithAttributes(PatientFile.java:239)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.model.ContextObjects.PatientFile.<init>(PatientFile.java:180)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.model.ContextObjects.ObjectInstance.objectInstanceWithClass(ObjectInstance.java:136)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.model.ContextObjects.ObjectInstance.objectInstancesWithClass(ObjectInstance.java:158)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.MedableResponse.getParsedDataAs(MedableResponse.java:42)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.API.APIClient$58.success(APIClient.java:4323)
03-22 12:59:32.898 28344-28344/com.example.smilio W/System.err:     at com.medable.AndroidSDK.API.APIClient$58.success(APIClient.java:4318)
03-22 12:59:32.899 28344-28344/com.example.smilio W/System.err:     at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
03-22 12:59:32.899 28344-28344/com.example.smilio W/System.err:     at android.os.Handler.handleCallback(Handler.java:808)
03-22 12:59:32.899 28344-28344/com.example.smilio W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:103)
03-22 12:59:32.899 28344-28344/com.example.smilio W/System.err:     at android.os.Looper.loop(Looper.java:193)
03-22 12:59:32.900 28344-28344/com.example.smilio W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5364)
03-22 12:59:32.903 28344-28344/com.example.smilio W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
03-22 12:59:32.903 28344-28344/com.example.smilio W/System.err:     at java.lang.reflect.Method.invoke(Method.java:515)
03-22 12:59:32.903 28344-28344/com.example.smilio W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
03-22 12:59:32.903 28344-28344/com.example.smilio W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
03-22 12:59:32.904 28344-28344/com.example.smilio W/System.err:     at dalvik.system.NativeStart.main(Native Method)

**Comment by billybiset** [comment]
@kord2003 Thank you for bringing this up.

It appears our date parser would always assume a long date format and it wouldn't parse short ones.

I'll fix this shortly and produce a new version of the library.

**Comment by billybiset** [comment]
Also note that I see in our implementation files that these are the pattern strings:

```java
    private static final String kShortPattern = "yyyy-MM-dd";
    private static final String kLongPattern = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
```

However, the short DateParseFormat enum has a misleading name:

```java
public enum DateParseFormat
{
    YYYY_DD_MM(1),
    Long(2);
```

Notice the enum is called ```YYYY_DD_MM``` yet the format string puts the month before the day ```"yyyy-MM-dd"```.

I'll also change the enum to match this, which might cause existing code to fail to compile (all that will be needed will be to change the code to the right enum).

**Comment by billybiset** [comment]
@kord2003 Try 1.0.1 to see if it fixed the issue
